# site settings
title: This new adventure
subtitle: 1+1 = 3
email: myemail@gmail.com
description: Thank you to all of you<br />
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: https://jivane.github.io # the base hostname & protocol for your site
author: Jivane & Mylene
street_address: 1234 Somewhere Road
city: Saint Cloud
state: Haut de Seine
zip_code: 92210
country: France

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# build settings
markdown: kramdown

sass:
  style: compressed
