# site settings
title: This new adventure
subtitle: 1+1 = 3
description: Thank you to all of you<br />
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: https://jivane.github.io # the base hostname & protocol for your site
author: Jivane & Mylene

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 1

# build settings
markdown: kramdown

sass:
  style: compressed
